<?php

namespace Quitenoisemaker\ShippingTracker\Support;

class StatusMapper
{
    protected static $map = [
        'sendbox' => [
            'pending' => 'pending',
            'delivery_started' => 'in_transit',
            'in_transit' => 'in_transit',
            'delivered' => 'delivered',
            'pickup_started' => 'in_transit',
            'pickup_completed' => 'in_transit',
            'cancelled' => 'cancelled',
        ],
        'cargoplug' => [
            'received_abroad' => 'in_transit',
            'pending_initiation' => 'pending',
            'initiated' => 'pending',
            'paid' => 'paid',
            'in_transit' => 'in_transit',
            'received_lagos' => 'in_transit',
            'dispatch_assigned' => 'in_transit',
            'dispatched' => 'in_transit',
            'delivered' => 'delivered',
            'shipment_delay' => 'on_hold',
            'shipment_on_hold' => 'on_hold',
            'undergoing_customs_clearance' => 'on_hold',
            'initiating' => 'pending',
        ],
        'dhl' => [
            "PICKED UP FROM SENDER" => "in_transit",
            "SHIPMENT CANCELED" => "cancelled",
            "ARRIVED AT ORIGIN PROCESSING FACILITY" => "in_transit",
            "PACKAGE SCREENED SUCCESSFULLY" => "in_transit",
            "PACKAGE SCREENING EXCEPTION - CANNOT BE SHIPPED INTERNATIONAL" => "on_hold",
            "PACKAGE SCREENING EXCEPTION - RETURNING TO SHIPPER" => "cancelled",
            "PICK UP BOOKED" => "pending",
            "SHIPMENT DEPARTED SELLERS ORIGIN TERMINAL" => "in_transit",
            "PARTNER EVENT - DEPARTED PARTNER FACILITY" => "in_transit",
            "PACKAGE DEPARTED SCREENING FACILITY" => "in_transit",
            "RECEIVED BY CARRIER FOR TRANSPORT" => "in_transit",
            "ARRIVAL SERVICE POINT" => "in_transit",
            "DEPARTURE DHL DISTRIBUTION CENTER" => "in_transit",
            "ARRIVAL SORT LOCATION" => "in_transit",
            "OUT FOR PARCEL COLLECTION" => "in_transit",
            "PICKED UP" => "in_transit",
            "UNSUCCESSFUL COLLECTION ATTEMPT" => "on_hold",
            "PICK UP RESCHEDULED" => "pending",
            "DELIVERED" => "delivered",
            "OUT FOR DELIVERY" => "in_transit",
            "ATTEMPTED DELIVERY" => "on_hold",
            "RETURNED TO WAREHOUSE" => "cancelled",
            "RETURN TO SENDER" => "cancelled",
            "HELD FOR COLLECTION" => "pending",
            "PARCEL HANDED TO COURIER" => "in_transit",
            "CUSTOMS ENTRY ACCEPTED" => "in_transit",
            "CUSTOMS CLEARED" => "in_transit",
            "CUSTOMS CLEARANCE PROCESSING COMPLETE" => "in_transit",
            "CUSTOMS CLEARANCE DELAY" => "on_hold",
            "CUSTOMS PROCESSING DELAY" => "on_hold",
            "PENDING COMPLETION OF CUSTOMS CLEARANCE" => "on_hold",
            "ARRIVAL AT DESTINATION DHL ECOMMERCE FACILITY" => "in_transit",
            "PROCESSED AT DESTINATION FACILITY" => "in_transit",
            "PROCESSED AT TRANSIT FACILITY" => "in_transit",
            "ARRIVAL DESTINATION DHL DISTRIBUTION CENTER" => "in_transit",
            "DEPARTURE DESTINATION DHL DISTRIBUTION CENTER" => "in_transit",
            "DEPARTURE TRANSIT DHL DISTRIBUTION CENTER" => "in_transit",
            "PROCESSED AT DESTINATION DHL DISTRIBUTION CENTER" => "in_transit",
            "PROCESSED AT TRANSIT DHL DISTRIBUTION CENTER" => "in_transit",
            "ARRIVAL DESTINATION DHL DISTRIBUTION CENTER" => "in_transit",
            "ARRIVAL TRANSIT DHL DISTRIBUTION CENTER" => "in_transit",
            "PROCESSED AT DESTINATION FACILITY - CUSTOMER PICKUP" => "in_transit",
            "ENROUTE TO DELIVERY DESTINATION" => "in_transit",
            "DEPARTURE FOR DELIVERY DESTINATION" => "in_transit",
            "TRANSFERRED THROUGH DHL FACILITY" => "in_transit",
            "PROCESSED AT DESTINATION FACILITY - ON FORWARD TO THIRD PARTY AGENT" => "in_transit",
            "PARCEL ARRIVED AT DELIVERY FACILITY" => "in_transit",
            "PROCESSED AT DESTINATION FACILITY - ON FORWARD FOR DELIVERY" => "in_transit",
            "PARCEL IS OUT FOR DELIVERY" => "in_transit",
            "ARRIVAL DESTINATION SERVICE AREA" => "in_transit",
            "DEPARTURE DESTINATION SERVICE AREA" => "in_transit",
            "DEPARTURE ORIGIN SERVICE AREA" => "in_transit",
            "PROCESSED AT DELIVERY FACILITY" => "in_transit",
            "ARRIVAL DESTINATION COUNTRY DISTRIBUTION CENTER" => "in_transit",
            "DEPARTURE DESTINATION COUNTRY DISTRIBUTION CENTER" => "in_transit",
            "PROCESSED AT DESTINATION COUNTRY DISTRIBUTION CENTER" => "in_transit",
            "ARRIVAL DESTINATION COUNTRY FACILITY" => "in_transit",
            "DEPARTURE DESTINATION COUNTRY FACILITY" => "in_transit",
            "ARRIVAL DESTINATION COUNTRY FACILITY - PENDING COMPLETION OF CUSTOMS CLEARANCE" => "on_hold",
            "ARRIVAL DESTINATION FACILITY" => "in_transit",
            "ARRIVAL AT DELIVERY FACILITY" => "in_transit",
            "DEPARTURE ORIGIN DHL DISTRIBUTION CENTER" => "in_transit",
            "PROCESSED AT ORIGIN FACILITY" => "in_transit",
            "DEPARTURE ORIGIN COUNTRY FACILITY" => "in_transit",
            "ARRIVAL ORIGIN FACILITY" => "in_transit",
            "ARRIVAL ORIGIN COUNTRY DISTRIBUTION CENTER" => "in_transit",
            "DEPARTURE ORIGIN COUNTRY DISTRIBUTION CENTER" => "in_transit",
            "PROCESSED AT ORIGIN COUNTRY DISTRIBUTION CENTER" => "in_transit",
            "DEPARTURE ORIGIN COUNTRY FACILITY" => "in_transit",
            "PROCESSED AT ORIGIN COUNTRY FACILITY" => "in_transit",
            "ARRIVAL ORIGIN COUNTRY FACILITY" => "in_transit",
            "ARRIVAL TRANSIT FACILITY" => "in_transit",
            "DEPARTURE TRANSIT FACILITY" => "in_transit",
            "PROCESSED AT TRANSIT FACILITY" => "in_transit",
            "PROCESSED AT TRANSIT COUNTRY DISTRIBUTION CENTER" => "in_transit",
            "ARRIVAL TRANSIT COUNTRY DISTRIBUTION CENTER" => "in_transit",
            "DEPARTURE TRANSIT COUNTRY DISTRIBUTION CENTER" => "in_transit",
            "ARRIVAL TRANSIT COUNTRY FACILITY" => "in_transit",
            "DEPARTURE TRANSIT COUNTRY FACILITY" => "in_transit",
            "PROCESSED AT TRANSIT COUNTRY FACILITY" => "in_transit",
            "ARRIVAL COUNTRY FACILITY" => "in_transit",
            "DEPARTURE COUNTRY FACILITY" => "in_transit",
            "ARRIVAL COUNTRY DISTRIBUTION CENTER" => "in_transit",
            "DEPARTURE COUNTRY DISTRIBUTION CENTER" => "in_transit",
            "PROCESSED AT COUNTRY DISTRIBUTION CENTER" => "in_transit",
            "ARRIVAL FACILITY" => "in_transit",
            "DEPARTURE FACILITY" => "in_transit",
            "PROCESSED AT FACILITY" => "in_transit",
            "ARRIVAL DHL DISTRIBUTION CENTER" => "in_transit",
            "DEPARTURE DHL FACILITY" => "in_transit",
            "PROCESSED AT DHL FACILITY" => "in_transit",
            "DEPARTURE COUNTRY DHL FACILITY" => "in_transit",
            "PROCESSED AT COUNTRY DHL FACILITY" => "in_transit",
            "ARRIVAL COUNTRY DHL FACILITY" => "in_transit",
            "ARRIVAL AT ORIGIN FACILITY" => "in_transit",
            "ARRIVAL AT ORIGIN COUNTRY FACILITY" => "in_transit",
            "PROCESSED AT ORIGIN DHL FACILITY" => "in_transit",
            "DEPARTURE ORIGIN FACILITY" => "in_transit",
            "ARRIVAL ORIGIN DHL FACILITY" => "in_transit",
            "DEPARTURE ORIGIN DHL FACILITY" => "in_transit",
            "PROCESSED AT ORIGIN DHL FACILITY" => "in_transit",
            "PROCESSED AT ORIGIN FACILITY - CUSTOMER PICKUP" => "in_transit",
            "CUSTOMER PICKUP" => "delivered",
            "CONSIGNEE PICKUP" => "delivered",
            "delivered" => "delivered",
            "transit" => "in_transit",
            "pre-transit" => "pending",
            "failure" => "on_hold",
            "Agreed delivery" => "pending",
            "Arrived facility" => "in_transit",
            "Arrival in delivery facility" => "in_transit",
            "Awaiting cnee collection" => "pending",
            "Bad address" => "on_hold",
            "Closed on arrival" => "on_hold",
            "Clearance release" => "in_transit",
            "Customs status updated" => "on_hold",
            "Broker release" => "on_hold",
            "Customer broker notified" => "on_hold",
            "Refused delivery" => "cancelled",
            "Returned to consignor" => "cancelled",
            "With delivering courier" => "in_transit",
            "Processed at location" => "in_transit",
            "Shipment pick up" => "pending",
            "Arrived at sort facility" => "in_transit",
            "Departed facility" => "in_transit",
            "Held at DHL location" => "on_hold",
            "On hold" => "on_hold",
            "Payment received" => "pending",
            "Shipment on hold" => "on_hold",
            "Shipment received" => "pending",
            "Exception" => "on_hold",
            "Transferred through DHL facility" => "in_transit",
            "Processed at facility" => "in_transit",
            "Arrived at facility" => "in_transit",
            "Departed from facility" => "in_transit",
            "Shipment picked up" => "pending",
            "Shipment departed" => "in_transit",
            "Shipment processed" => "in_transit",
            "in customs" => "on_hold",
            "out for delivery" => "in_transit",
        ],

    ];

    /**
     * Normalize a status based on the provider.
     *
     * @param string $provider
     * @param string $status
     * @return string
     */
    public static function normalize(string $provider, string $status): string
    {
        $normalizedStatus = str_replace(' ', '_', strtolower($status));
        return static::$map[strtolower($provider)][$normalizedStatus] ?? 'unknown';
    }
}
