blank_issues_enabled: false
contact_links:
  - name: GitHub Issues
    url: https://github.com/quitenoisemaker/shipping-tracker/issues
    about: Check existing issues before submitting.
  - name: Email Support
    url: mailto:samsonojugo@gmail.com
    about: For private inquiries, contact us via email.ss